name: Trigger Webhook

on:
  push:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook
        run: |
          curl -X POST "https://webhook.site/f4023694-8fa4-45e7-8f75-d14232f63351"